### ISSUE TITLE
你代理方法调用的时候方法名写错了

### ISSUE THREAD

**Issue by Ella-Sun** [xiaozhuxiong121/PGPickerView#3]
NSString *text = @"";
       if ([self.delegate respondsToSelector:@selector(pickerView:middleTextSpaceForcomponent:)]) {
            text = [self.delegate pickerView:self middleTextForcomponent:i];
        }

**Comment by xiaozhuxiong121** [comment]
什么意思？

**Comment by Ella-Sun** [comment]
if ([self.delegate respondsToSelector:@selector(pickerView:middleTextSpaceForcomponent:)]) {
判断是middleTextSpaceForcomponent，多了space

**Comment by xiaozhuxiong121** [comment]
谢谢反馈，新版本已修复
