### ISSUE TITLE
咋不再封装一下呢PickerView那种

### ISSUE THREAD

**Issue by GrapeFruitJun** [xiaozhuxiong121/PGPickerView#8]

**Comment by xiaozhuxiong121** [comment]
什么意思？

**Comment by GrapeFruitJun** [comment]
弹出动画,PGDatePickManager里面管理PGDatePicker和PGPickerView

**Comment by xiaozhuxiong121** [comment]
用PGDatePickManager是因为里面用到了PGDatePicker和PGPickerView，所以就又封装了一层，
而PGPickerView只是一个单独的控件，所以就没有在封装
